name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.15'
    
      - name: Install HTMLValidator
        run: npm install html-validator-cli -g

      - name: Check html
        run: html-validator --file=game.html --verbose
        
      - name: Install babel eslint
        run: npm install --save-dev eslint @babel/core @babel/eslint-parser @babel/eslint-plugin @babel/preset-env @babel/plugin-syntax-class-properties
      
      - name: Check game.js
        run: ./node_modules/.bin/eslint --format codeframe --color game.js

      - name: Check tournament.js
        run: ./node_modules/.bin/eslint --format codeframe --color tournament.js --env-info

