name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15'
    
      - name: Install HTMLValidator
        run: npm install html-validator-cli -g
        
      - name: Check html
        run: html-validator --file=game.html --verbose
        
      - name: Install babel eslint
        run: yarn add eslint @babel/core @babel/eslint-parser @babel/eslint-plugin @babel/preset-env --dev
      
      - name: Check js
        run: yarn run eslint --format codeframe --color game.js
      
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: game.html

      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ format('[Click here to preview HTML page in browser]({0})', steps.html_preview.outputs.url) }}
        
